K =3;
G1=7;
G2=5;
msg = [1 1 0 0 1 0];
trellis = poly2trellis(K,[G1,G2]);
coded = convenc(msg,trellis);
tblen=length(msg);
decoded = vitdec(coded,trellis,tblen,'trunc','hard');
disp('Decoded Output:');
disp(decoded);
